# Generated by Django 4.2.3 on 2023-07-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='title',
            new_name='cooking_method',
        ),
        migrations.AlterField(
            model_name='information',
            name='source',
            field=models.URLField(verbose_name='source'),
        ),
    ]
