# Generated by Django 4.2.3 on 2023-07-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_rename_states_cookingstep_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cooking_time',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='information',
            name='preparation_time',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='information',
            name='rest_period',
            field=models.CharField(max_length=128),
        ),
    ]
