# Generated by Django 4.2.3 on 2023-07-18 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='lu')),
                ('name', models.CharField(default='inconu', max_length=128, verbose_name="nom de l'éxpediteur")),
                ('email', models.EmailField(max_length=254, verbose_name='adresse mail')),
                ('subject', models.CharField(blank=True, max_length=1024, verbose_name='sujet')),
                ('content', models.TextField(max_length=128000, verbose_name='contenu du message')),
                ('sending_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
